version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/filehost
      - JWT_SECRET=changeme
      - MAX_FILE_SIZE=1000000000000  # 100MB in bytes
    volumes:
      - storage_data:/app/storage
    ports:
      - "6002:8080"
    depends_on:
      - mongodb
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "6003:80"
    networks:
      - app-network
    depends_on:
      - backend

  mongodb:
    image: mongo:latest
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data:
  storage_data:
    driver: local